export const FORM_PROJECT = "FORM_PROJECT";
export const GET_PROJECTS = "GET_PROJECTS";
export const POST_PROJECT = "POST_PROJECT";
export const VALIDATE_FORM = "VALIDATE_FORM";
export const ACTUAL_PROJECT = "ACTUAL_PROJECT";
export const DELETE_PROJECT = "ACTUAL_PROJECT";